spring:
  application:
    name: wechat-bot
  datasource:
    url: jdbc:mysql://localhost:3306/chat_rebot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 'ENC(dACLo0JBSpU/UPCQvgFsz0xY4fnHmT5iV22rwpQYqmet3qchM2VWao5ZUh+eR6OL)'
#    password: 'ENC(RcWxW8QNKpwzxxdfFjxyhMXza4KRZQbAMP+L2rbieWmDA7mhH/zImAJcIU3B8hsI)'
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      apiKey: 'ENC(HHCgxEk6VynGMKwiGnL02Sh8bo8ZoNMa3kTQTLW8chAIQZ4BpuC9gk2EwuQhRyyUqqUpg4JjdbrqX11b/G1hgDxL9BbX0P8t5N1Xy/eIc2KoshmKjqxf5ZQ5ZIWMLNuU)'
      baseUrl: https://www.henapi.top
      chat:
        options:
          model: gpt-4o-mini

jasypt:
  encryptor:
    algorithm: PBEWithHmacSHA512AndAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

openai:
  api:
    key: 'ENC(VnJBkw2L1ODTbLgdO7gvd9LRGQfQg5eBMNhjD9ax6G5ZjbAETz1eqCB9/twifbFDGyxTC2HNmheLjvxe9D42G0etBeyNiOsDxYkj1OFQA8etBEn2iw6Wsg68jQCECk+3)'
    #key: 'ENC(HHCgxEk6VynGMKwiGnL02Sh8bo8ZoNMa3kTQTLW8chAIQZ4BpuC9gk2EwuQhRyyUqqUpg4JjdbrqX11b/G1hgDxL9BbX0P8t5N1Xy/eIc2KoshmKjqxf5ZQ5ZIWMLNuU)'
    url: https://api.openai-hk.com
    #url: https://www.henapi.top
    model-name: gpt-4o-mini
    count: 2
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: boss.jieyin.wechatbot.model

sign:
  secret-key: 'ENC(h/8yoGkJjrkzF1mMa3diSMF0awGyfWPkfmYZHwyjtV3ANx1awZcrmKOvjnhC2ZN/ps8as0yqS7CWLhoxwoVXeICofxtZ3U4nUuWahGg+FDw=)'
#  secret-key:
logging:
  level:
    root: info
    boss.jieyin.wechatbot: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"


